/*
 * rsp_es9.c -- ES9+ (LPA -- SM-DP+), SGP.22 v2.6 section 5.6: this file
 * currently implements only InitiateAuthentication (section 5.6.1), the
 * first of three ES9+ functions this library implements as the SM-DP+
 * role (AuthenticateClient and GetBoundProfilePackage are later tasks).
 *
 * Section 5.6.1 itself defers the exact content it hands back to section
 * 5.7.13 "ES10b.AuthenticateServer", which is what the eUICC actually
 * receives once the LPA relays this function's response on:
 *
 *   ServerSigned1 ::= SEQUENCE {
 *       transactionId   [0] TransactionId,   -- generated by the SM-DP+
 *       euiccChallenge  [1] Octet16,         -- echoed back unchanged
 *       serverAddress   [3] UTF8String,      -- the SM-DP+'s own FQDN
 *       serverChallenge [4] Octet16          -- generated by the SM-DP+
 *   }
 *
 * "serverSignature1 SHALL be created using the private key associated to
 * the RSP Server Certificate for authentication" (5.7.13) -- CERT.DPauth.
 * ECDSA, rsp_pki_dp(0, ...), never DPpb (role 1): DPpb signs the Bound
 * Profile Package (rsp_bpp_build), a different key for a different
 * purpose the eUICC has no reason to accept here.
 *
 * The response this file returns (*resp / *resp_len) is the DER encoding
 * of the generated InitiateAuthenticationOkEs9 type: exactly the five
 * fields Table 36 lists (transactionId, serverSigned1, serverSignature1,
 * euiccCiPKIdToBeUsed, serverCertificate), "returned as encoded data
 * objects including the tags defined for them in the
 * AuthenticateServerRequest data object" (5.6.1 Table 36, NOTE 1).
 * ctxParams1 is deliberately not part of it -- that field is the LPA's
 * own contribution to the later AuthenticateServer call, not something
 * the SM-DP+ hands back from InitiateAuthentication, and
 * InitiateAuthenticationOkEs9 (unlike AuthenticateServerRequest) has no
 * such field to fill in the first place.
 *
 * Two judgement calls, made because section 5.6.1's own interface gives
 * this function nothing to work with for them -- see task-2-report.md
 * (euicc-tools' write-path SDD folder) for the full account:
 *
 *   - serverAddress has no input parameter at all: this function does
 *     not even accept the LPA-supplied smdpAddress Table 35 describes,
 *     so there is neither a real address to embed nor a mismatch to
 *     check. RSP_ES9_SMDP_ADDRESS_PLACEHOLDER below (RFC 2606's
 *     reserved-for-example ".invalid" TLD) is signed in its place --
 *     real bytes on the wire and genuinely signed, but not a real SM-DP+
 *     address. Whichever task first wires up server configuration
 *     should replace it with one, not extend it.
 *   - euiccCiPKIdToBeUsed: section 5.6.1 has the SM-DP+ "select the CI
 *     ... according to the priority provided by the eUICC" among
 *     possibly several supported CI Public Keys. This library supports
 *     exactly one CI -- the compiled-in SGP.26 test issuer,
 *     rsp_pki_test_ci -- so there is nothing to select among. Its own
 *     Subject Key Identifier is extracted from the certificate itself
 *     (not hand-copied as a second literal), so it cannot silently drift
 *     from what rsp_pki_verify actually chains DPauth/DPpb against. This
 *     is used unconditionally, without checking it even appears in the
 *     caller's euiccInfo1 -- a real check once a second CI ever exists,
 *     a tautology while only one does.
 *
 * serverChallenge is not a judgement call: section 5.6.1 says to
 * "Generate a serverChallenge", the same verb it uses for transactionId,
 * and this function does so with real entropy. Unlike transactionId,
 * nothing about session replay depends on serverChallenge being
 * caller-supplied (see include/rsp.h's own note on why transactionId
 * is), so it is generated the way the spec actually describes, not
 * threaded through as another parameter.
 */
#include "rsp.h"
#include "rsp_internal.h"

#include <stdlib.h>
#include <string.h>

#include "mbedtls/ctr_drbg.h"
#include "mbedtls/entropy.h"
#include "mbedtls/platform_util.h"
#include "mbedtls/x509_crt.h"

#include "Certificate.h"
#include "EUICCInfo1.h"
#include "InitiateAuthenticationOkEs9.h"
#include "ServerSigned1.h"

/* See this file's own top comment: no smdp_address input exists yet, so
 * this fixed, obviously-fake FQDN (RFC 2606 reserves ".invalid" for
 * exactly this -- content that must never resolve) stands in for it.
 * Real bytes, genuinely signed, but not a real SM-DP+ address. */
static const char RSP_ES9_SMDP_ADDRESS_PLACEHOLDER[] =
    "smdp-address-placeholder.invalid";

/* One RSP session's server-side state -- see the typedef's own doc
 * comment in rsp.h. Nothing in it is secret yet (transactionId and both
 * challenges cross the wire in the clear); rsp_dp_session_free wipes it
 * anyway, ahead of the session keys a later task lands here, rather than
 * waiting for that task to notice this one used plain free(). */
struct rsp_dp_session {
    uint8_t transaction_id[16];
    uint8_t euicc_challenge[16];
    uint8_t server_challenge[16];
};

/* der_encode's callback interface, and a malloc'ed-buffer wrapper around
 * it. This is deliberately a second copy of src/rsp_bpp.c's own
 * der_encode_alloc/der_collect, not a shared one promoted to
 * rsp_internal.h: that header is also included, unchanged, by
 * euicc-lpa's src/rsp_es10.c through the vendored submodule, and this
 * pair's bodies name asn_TYPE_descriptor_t/der_encode/asn_enc_rval_t --
 * types this header does not otherwise pull in. Adding them to a header
 * every includer already compiles risks breaking euicc-lpa's build over
 * a tidiness gain confined to this one file; rsp_growbuf_t (which this
 * does reuse) has no such dependency, which is exactly why it, and only
 * it, already lives in rsp_internal.h. */
static int der_collect(const void *buf, size_t n, void *key)
{
    return rsp_growbuf_append((rsp_growbuf_t *)key, buf, n) == 0 ? 0 : -1;
}

static int der_encode_alloc(asn_TYPE_descriptor_t *td, const void *sptr,
                             uint8_t **out, size_t *out_len)
{
    rsp_growbuf_t g;
    asn_enc_rval_t r;

    memset(&g, 0, sizeof g);
    r = der_encode(td, sptr, der_collect, &g);
    if (r.encoded < 0) {
        rsp_growbuf_free(&g);
        return -1;
    }
    *out = g.buf;
    *out_len = g.len;
    return 0;
}

int rsp_dp_initiate_authentication(
        const uint8_t *euicc_challenge, size_t challenge_len,
        const uint8_t *euicc_info1, size_t info1_len,
        const uint8_t transaction_id[16],
        rsp_dp_session_t **out,
        uint8_t **resp, size_t *resp_len)
{
    InitiateAuthenticationOkEs9_t ok;
    EUICCInfo1_t info1_tmp;
    rsp_credential_t dpauth;
    mbedtls_x509_crt ci_crt;
    mbedtls_entropy_context ent;
    mbedtls_ctr_drbg_context drbg;
    const uint8_t *ci_der;
    size_t ci_len;
    uint8_t *ss1_der = NULL;
    size_t ss1_der_len = 0;
    uint8_t sig[64];
    uint8_t server_challenge[16];
    int have_dpauth = 0;
    int have_rng = 0;
    int ret = -1;

    memset(&ok, 0, sizeof ok);
    memset(&info1_tmp, 0, sizeof info1_tmp);
    memset(&dpauth, 0, sizeof dpauth);
    mbedtls_x509_crt_init(&ci_crt);

    if (!euicc_challenge || challenge_len != 16 || !euicc_info1 ||
        info1_len == 0 || !transaction_id || !out || !resp || !resp_len) {
        goto out;
    }

    /* Reject euiccInfo1 that does not even decode -- Table 35 marks it
     * mandatory, and a caller boundary is exactly where garbage input
     * should be refused rather than silently ignored. Not otherwise
     * used: this library has only one CI to offer (see this file's top
     * comment), so euiccInfo1's own CI-Public-Key-ID lists have nothing
     * to select among yet, and its eUICC identity fields are what a
     * later step's euiccSigned1/euiccInfo2 learns, not this one. */
    {
        void *p = &info1_tmp;
        asn_dec_rval_t r = ber_decode(NULL, &asn_DEF_EUICCInfo1, &p,
                                       euicc_info1, info1_len);
        if (r.code != RC_OK) {
            goto out;
        }
    }

    have_rng = rsp_rng_init(&ent, &drbg, "euicc-rsp/rsp_es9") == 0;
    if (!have_rng ||
        mbedtls_ctr_drbg_random(&drbg, server_challenge,
                                 sizeof server_challenge) != 0) {
        goto out;
    }

    /* ServerSigned1, built directly inside ok: 5.7.13's "serverSignature1
     * SHALL apply on serverSigned1 data object" means the signed bytes
     * are ServerSigned1's own DER encoding -- exactly what encoding
     * ok.serverSigned1 alone, via its own type descriptor, produces
     * before the rest of ok is filled in. ServerSigned1 carries no tag
     * of its own (rsp-2.5.asn) and AUTOMATIC TAGS does not touch it as a
     * field either (InitiateAuthenticationOkEs9's own serverSignature1
     * member already carries an explicit [APPLICATION 55], which is
     * exactly the condition under which X.680 automatic tagging leaves
     * every sibling field's own natural tag alone) -- so this same
     * struct's encoding is byte-identical whether encoded here, alone,
     * or later as part of the whole ok. */
    if (OCTET_STRING_fromBuf(&ok.serverSigned1.transactionId,
                              (const char *)transaction_id, 16) != 0 ||
        OCTET_STRING_fromBuf(&ok.serverSigned1.euiccChallenge,
                              (const char *)euicc_challenge,
                              (int)challenge_len) != 0 ||
        OCTET_STRING_fromBuf(&ok.serverSigned1.serverAddress,
                              RSP_ES9_SMDP_ADDRESS_PLACEHOLDER,
                              (int)(sizeof RSP_ES9_SMDP_ADDRESS_PLACEHOLDER - 1)) != 0 ||
        OCTET_STRING_fromBuf(&ok.serverSigned1.serverChallenge,
                              (const char *)server_challenge,
                              sizeof server_challenge) != 0) {
        goto out;
    }

    if (der_encode_alloc(&asn_DEF_ServerSigned1, &ok.serverSigned1,
                          &ss1_der, &ss1_der_len) != 0) {
        goto out;
    }

    if (rsp_pki_dp(0, &dpauth) != 0) { /* DPauth, not DPpb -- see top comment */
        goto out;
    }
    have_dpauth = 1;

    if (rsp_sign(&dpauth, ss1_der, ss1_der_len, sig) != 0) {
        goto out;
    }

    if (rsp_pki_test_ci(&ci_der, &ci_len) != 0) {
        goto out;
    }
    if (mbedtls_x509_crt_parse_der_with_ext_cb(&ci_crt, ci_der, ci_len, 1,
                                                rsp_accept_certificate_policies,
                                                NULL) != 0) {
        goto out;
    }
    if (ci_crt.subject_key_id.len == 0) {
        goto out; /* the compiled-in test CI is expected to carry one */
    }

    if (OCTET_STRING_fromBuf(&ok.transactionId,
                              (const char *)transaction_id, 16) != 0 ||
        OCTET_STRING_fromBuf(&ok.serverSignature1,
                              (const char *)sig, sizeof sig) != 0 ||
        OCTET_STRING_fromBuf(&ok.euiccCiPKIdToBeUsed,
                              (const char *)ci_crt.subject_key_id.p,
                              (int)ci_crt.subject_key_id.len) != 0) {
        goto out;
    }

    /* Decode CERT.DPauth.ECDSA's own DER (already loaded, already what
     * was just signed with) into ok.serverCertificate in place: passing
     * a non-NULL *struct_ptr makes every asn1c SEQUENCE decoder (see
     * dist/constr_SEQUENCE.c: "st = *struct_ptr; if (st == 0) { st =
     * *struct_ptr = CALLOC(...); }") fill the memory already there
     * instead of allocating a new one -- ok.serverCertificate, already
     * zeroed above, is exactly such memory. No separate certificate
     * struct, no shallow copy, no second free to keep straight. */
    {
        void *p = &ok.serverCertificate;
        asn_dec_rval_t r = ber_decode(NULL, &asn_DEF_Certificate, &p,
                                       dpauth.der, dpauth.der_len);
        if (r.code != RC_OK) {
            goto out;
        }
    }

    if (der_encode_alloc(&asn_DEF_InitiateAuthenticationOkEs9, &ok,
                          resp, resp_len) != 0) {
        goto out;
    }

    {
        rsp_dp_session_t *sess = malloc(sizeof *sess);
        if (!sess) {
            free(*resp);
            *resp = NULL;
            *resp_len = 0;
            goto out;
        }
        memcpy(sess->transaction_id, transaction_id, 16);
        memcpy(sess->euicc_challenge, euicc_challenge, 16);
        memcpy(sess->server_challenge, server_challenge,
               sizeof server_challenge);
        *out = sess;
    }

    ret = 0;

out:
    if (have_dpauth) {
        rsp_credential_free(&dpauth);
    }
    if (have_rng) {
        mbedtls_ctr_drbg_free(&drbg);
        mbedtls_entropy_free(&ent);
    }
    mbedtls_x509_crt_free(&ci_crt);
    ASN_STRUCT_RESET(asn_DEF_EUICCInfo1, &info1_tmp);
    ASN_STRUCT_RESET(asn_DEF_InitiateAuthenticationOkEs9, &ok);
    free(ss1_der);
    return ret;
}

void rsp_dp_session_free(rsp_dp_session_t *s)
{
    if (!s) {
        return;
    }
    mbedtls_platform_zeroize(s, sizeof *s);
    free(s);
}
