/*
 * rsp_pki.c -- the SM-DP+ credentials this library signs with.
 *
 * There is no minting here. GSMA's SGP.26 test material already contains
 * complete DPauth and DPpb certificates together with their secret keys,
 * signed by a Certificate Issuer that a test eUICC trusts. This file loads
 * that material and proves the two halves agree: the certificate chains to
 * the test CI, and the certificate's public key is the one the secret key
 * produces. A mismatch here is exactly the failure mode that would
 * otherwise only surface at the card, where the answer is a status word.
 *
 * The material is redistributed test data -- see testdata/sgp26/README.md.
 * It works on test eUICCs and nowhere else.
 */
#include "rsp.h"
#include "rsp_internal.h"

#include <stdlib.h>
#include <string.h>

#include "mbedtls/asn1.h"
#include "mbedtls/ctr_drbg.h"
#include "mbedtls/ecp.h"
#include "mbedtls/entropy.h"
#include "mbedtls/oid.h"
#include "mbedtls/pk.h"
#include "mbedtls/platform_util.h"
#include "mbedtls/x509_crt.h"

/* Generated by the Makefile (build/sgp26_material.c) from the files in
 * testdata/sgp26/, with `xxd -i`. Not committed: the DER and PEM files are
 * the single source, this is a derived build artifact like dist/. */
extern const unsigned char rsp_sgp26_ci_der[];
extern const unsigned int  rsp_sgp26_ci_der_len;
extern const unsigned char rsp_sgp26_dpauth_der[];
extern const unsigned int  rsp_sgp26_dpauth_der_len;
extern const unsigned char rsp_sgp26_dpauth_key_pem[];
extern const unsigned int  rsp_sgp26_dpauth_key_pem_len;
extern const unsigned char rsp_sgp26_dppb_der[];
extern const unsigned int  rsp_sgp26_dppb_der_len;
extern const unsigned char rsp_sgp26_dppb_key_pem[];
extern const unsigned int  rsp_sgp26_dppb_key_pem_len;

int rsp_pki_test_ci(const uint8_t **der, size_t *len)
{
    if (!der || !len) {
        return -1;
    }
    *der = rsp_sgp26_ci_der;
    *len = rsp_sgp26_ci_der_len;
    return 0;
}

int rsp_pki_dp(int role, rsp_credential_t *out)
{
    const unsigned char *cert_der, *key_pem;
    unsigned int cert_len, key_len;
    mbedtls_pk_context pk;
    int ret = -1;

    if (!out) {
        return -1;
    }
    memset(out, 0, sizeof *out);

    switch (role) {
    case 0: /* DPauth */
        cert_der = rsp_sgp26_dpauth_der;
        cert_len = rsp_sgp26_dpauth_der_len;
        key_pem  = rsp_sgp26_dpauth_key_pem;
        key_len  = rsp_sgp26_dpauth_key_pem_len;
        break;
    case 1: /* DPpb */
        cert_der = rsp_sgp26_dppb_der;
        cert_len = rsp_sgp26_dppb_der_len;
        key_pem  = rsp_sgp26_dppb_key_pem;
        key_len  = rsp_sgp26_dppb_key_pem_len;
        break;
    default:
        return -1;
    }

    out->der = malloc(cert_len);
    if (!out->der) {
        return -1;
    }
    memcpy(out->der, cert_der, cert_len);
    out->der_len = cert_len;

    mbedtls_pk_init(&pk);
    {
        /* key_pem is PEM text with an appended NUL (see the Makefile
         * rule): mbedtls_pk_parse_key requires keylen == strlen(pem) + 1
         * for PEM input. Parsing a SEC1 EC key recomputes its public
         * point via mbedtls_ecp_mul, which mbedTLS refuses to run with a
         * NULL RNG (MBEDTLS_ERR_ECP_BAD_INPUT_DATA) -- so a real RNG is
         * required here even though nothing is generated, only an
         * already-published test key is loaded. */
        mbedtls_entropy_context ent;
        mbedtls_ctr_drbg_context drbg;
        int rng_ok = rsp_rng_init(&ent, &drbg, "euicc-rsp/rsp_pki") == 0;
        int rc = rng_ok
            ? mbedtls_pk_parse_key(&pk, key_pem, key_len, NULL, 0,
                                    mbedtls_ctr_drbg_random, &drbg)
            : -1;
        mbedtls_ctr_drbg_free(&drbg);
        mbedtls_entropy_free(&ent);
        if (rc != 0 || !mbedtls_pk_can_do(&pk, MBEDTLS_PK_ECKEY)) {
            goto out;
        }
    }

    {
        mbedtls_ecp_keypair *kp = mbedtls_pk_ec(pk);
        size_t olen = 0;
        if (mbedtls_ecp_write_key_ext(kp, &olen, out->sk, sizeof out->sk) != 0 ||
            olen != sizeof out->sk) {
            goto out;
        }
    }

    ret = 0;

out:
    mbedtls_pk_free(&pk);
    if (ret != 0) {
        free(out->der);
        /* out is caller-visible, so this failure-path clear has the same
         * dead-store exposure as rsp_session_wipe's memset did (see
         * src/rsp_crypto.c) -- a store the compiler can prove nothing
         * reads again is free to drop. out->sk is not necessarily
         * populated with real key material on every path that reaches
         * here, but nothing about this call site can prove that, so it
         * is wiped like any other secret-shaped buffer this library
         * hands back. */
        mbedtls_platform_zeroize(out, sizeof *out);
    }
    return ret;
}

int rsp_pki_verify(const rsp_credential_t *c)
{
    const uint8_t *ci_der;
    size_t ci_len;
    mbedtls_x509_crt ci, leaf;
    mbedtls_entropy_context ent;
    mbedtls_ctr_drbg_context drbg;
    /* -2 by default: every failure up to and including the chain-of-trust
     * check is "the question was never reached" -- a malformed
     * credential, an unparseable certificate, an RNG that would not seed
     * -- see include/rsp.h's failure convention. mbedtls_x509_crt_verify
     * rejecting the chain and the sk/public-key mismatch check below are
     * the two places this project actually asked the question and got a
     * real "no"; each sets ret to -1 explicitly. */
    int ret = -2;
    int rng_ok;

    if (!c || !c->der || c->der_len == 0) {
        return -2;
    }
    if (rsp_pki_test_ci(&ci_der, &ci_len) != 0) {
        return -2;
    }

    mbedtls_x509_crt_init(&ci);
    mbedtls_x509_crt_init(&leaf);
    rng_ok = rsp_rng_init(&ent, &drbg, "euicc-rsp/rsp_pki") == 0;

    if (mbedtls_x509_crt_parse_der_with_ext_cb(&ci, ci_der, ci_len, 1,
                                                rsp_accept_certificate_policies,
                                                NULL) != 0) {
        goto out;
    }
    if (mbedtls_x509_crt_parse_der_with_ext_cb(&leaf, c->der, c->der_len, 1,
                                                rsp_accept_certificate_policies,
                                                NULL) != 0) {
        goto out;
    }

    {
        uint32_t flags = 0;
        if (mbedtls_x509_crt_verify(&leaf, &ci, NULL, NULL, &flags, NULL, NULL) != 0) {
            ret = -1; /* the question was asked: this does not chain to the test CI */
            goto out;
        }
    }

    if (!mbedtls_pk_can_do(&leaf.pk, MBEDTLS_PK_ECKEY) || !rng_ok) {
        goto out;
    }

    {
        /* mbedtls_ecp_keypair's fields are private in 3.6.2; the group
         * and the certificate's public point are pulled out through the
         * accessor mbedTLS provides for exactly this, mbedtls_ecp_export,
         * rather than reaching into the struct. */
        mbedtls_ecp_keypair *leaf_ec = mbedtls_pk_ec(leaf.pk);
        mbedtls_ecp_group grp;
        mbedtls_ecp_point cert_q, derived;
        mbedtls_mpi d;
        unsigned char buf_derived[MBEDTLS_ECP_MAX_PT_LEN];
        unsigned char buf_cert[MBEDTLS_ECP_MAX_PT_LEN];
        size_t len_derived = 0, len_cert = 0;
        int match = 0;

        mbedtls_ecp_group_init(&grp);
        mbedtls_ecp_point_init(&cert_q);
        mbedtls_ecp_point_init(&derived);
        mbedtls_mpi_init(&d);

        if (mbedtls_ecp_export(leaf_ec, &grp, NULL, &cert_q) == 0 &&
            mbedtls_mpi_read_binary(&d, c->sk, sizeof c->sk) == 0 &&
            mbedtls_ecp_mul(&grp, &derived, &d, &grp.G,
                             mbedtls_ctr_drbg_random, &drbg) == 0 &&
            mbedtls_ecp_point_write_binary(&grp, &derived,
                                            MBEDTLS_ECP_PF_UNCOMPRESSED,
                                            &len_derived, buf_derived,
                                            sizeof buf_derived) == 0 &&
            mbedtls_ecp_point_write_binary(&grp, &cert_q,
                                            MBEDTLS_ECP_PF_UNCOMPRESSED,
                                            &len_cert, buf_cert,
                                            sizeof buf_cert) == 0 &&
            len_derived == len_cert &&
            memcmp(buf_derived, buf_cert, len_derived) == 0) {
            match = 1;
        }

        mbedtls_ecp_group_free(&grp);
        mbedtls_ecp_point_free(&cert_q);
        mbedtls_ecp_point_free(&derived);
        mbedtls_mpi_free(&d);

        if (!match) {
            ret = -1; /* the question was asked: c->sk does not match this certificate */
            goto out;
        }
    }

    ret = 0;

out:
    mbedtls_x509_crt_free(&leaf);
    mbedtls_x509_crt_free(&ci);
    mbedtls_ctr_drbg_free(&drbg);
    mbedtls_entropy_free(&ent);
    return ret;
}

void rsp_credential_free(rsp_credential_t *c)
{
    if (!c) {
        return;
    }
    free(c->der);
    /* Task 4's fix report found the same dead-store pattern here: a
     * memset that -O2 is free to remove if it can prove nothing reads
     * the memory again. c is a pointer the caller still holds, so this
     * one likely was not actually eliminated (the compiler cannot
     * prove the caller never reads it after this function returns
     * without whole-program analysis) -- but mbedtls_platform_zeroize
     * removes the need to reason about that case by case. */
    mbedtls_platform_zeroize(c->sk, sizeof c->sk);
    memset(c, 0, sizeof *c);
}
